### ISSUE TITLE
关于如何判断一个用户是社区开发者还是企业开发者

### ISSUE THREAD

**Issue by bestony** [LCTT/Grank#13]
由于项目中包含了社区化分析，需要分析出不同项目的社区开发者和企业开发者的比重。

当前的方案是读取每一个 commit 的贡献者邮箱，并通过正则表达式拆分出邮件域

通过判断邮件域内是否包含特定关键词来判断是否是企业开发者。同时一个项目只能设置一个关键词，这样如果有百度的员工贡献了腾讯的项目，这个员工的贡献依然标记为社区开发者贡献。

不知是否有更好的方案，欢迎一同讨论。

**Comment by bestony** [comment]
从 0.0.14 版本开始，接受一个正则表达式作为判断，用户可以设定正则表达式来进行企业用户身份的判断。

```
[login]
token =

[social]
rule = gmail|inc|huawei|com

[time]
start_time = 2017-01-01
end_time = 2018-10-02

[rank]
top = 3
```

**Comment by wxy** [comment]
在交互过程中，可以根据显示的邮件域来手动输入新的邮件域（正则），也可以回车接受之前的规则。
目前也支持 askrule 参数，可以在交互过程中输入 `-` 不再询问新的规则。
