### ISSUE TITLE
社区化分析参数的预处理

### ISSUE THREAD

**Issue by bestony** [LCTT/Grank#23]
需求：对于特定的项目，不清楚邮件域是什么，可能需要提供一个列表进行辅助。

详细描述：

在进行社区化分析前，进行数据的预处理，提取出所有的邮件域，根据出现频次进行排序，展示列表给用户，由用户输入标记为企业的邮件域。

加入预处理前的顺序
1. 抓取数据
2. 活跃度分析
3. 社区化分析

加入预处理后的顺序

1. 抓取数据
2. 活跃度分析
3. 数据预处理
4. 社区化分析

> 此处预处理也可以提前到2 ，不过建议放在3 。后续可能可以设置分析类目。

补充信息

1. 展示 Top 10 的邮件域
2. 默认排除掉公共邮件域，比如 `gmail.com` `qq.com` `163.com` 等公共邮件域（此参数应当内置，同时允许用户指定，第一批可以考虑不实现，后续迭代实现。）
3. 在交互中，输出 Top 10 的列表，然后展示 1～10 ，用英文逗号或空格隔开。
4. 用户输入的获取可以参考：http://click.palletsprojects.com/en/7.x/prompts/

**Comment by wxy** [comment]
此需求优先级高

**Comment by bestony** [comment]
这个 ISSUE 我来跟进。
