### ISSUE TITLE
增加 clean 命令

### ISSUE THREAD

**Issue by wxy** [LCTT/Grank#5]
用于清除输出的数据。

**Comment by lujun9972** [comment]
这个项目是做什么的？

**Comment by bestony** [comment]
命令已经添加，但仍需优化。具体查看 1efd83e

优化方向

1. 提醒用户是否删除
2. 检测是否有非临时文件等其他文件，如果有则不删除。

**Comment by bestony** [comment]
已经发布 0.0.10 版本中包含了 `clean` 命令

**Comment by LuuMing** [comment]
#19 增加提醒
