### ISSUE TITLE
0.07 版疑似没读取 ini 配置

### ISSUE THREAD

**Issue by wxy** [LCTT/Grank#8]
在 grank login 时需要输入 token，在 organ 时没有读取分析时长。

**Comment by wxy** [comment]
不对，是我修改了时间范围。login 如你所说是不读取 ini 的。

**Comment by bestony** [comment]
grank login 的问题是设计考虑。

grank login 用于设置 用户登录的 token ，并不会提醒用户已经输出登录信息。如需检测用户是否已经登录，需要使用 `checklogin`

![image](https://user-images.githubusercontent.com/13283837/46266118-51382880-c55f-11e8-8019-6f052b22ddc4.png)
