### ISSUE TITLE
活跃度指数只需要保留小数点后2位即可

### ISSUE THREAD

**Issue by wxy** [LCTT/Grank#9]
如题

**Comment by LuuMing** [comment]
#18 修改活跃度指数为小数点后两位

**Comment by bestony** [comment]
@LuuMing 不仅仅是显示中的输出，还包含输出到文件时的内容。

涉及到的代码

https://github.com/LCTT/Grank/blob/cf205a6cd413a555f0e8a9f3ea629ee163a4a325/grank/libs/helpers.py#L192-L211


此外，你的 PR 仅修改了活跃度部分，未修改社区化的部分

https://github.com/LCTT/Grank/blob/cf205a6cd413a555f0e8a9f3ea629ee163a4a325/grank/script/social.py#L71

**Comment by LuuMing** [comment]
已修改，请查证
